name: base_mvvm
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Common
  get: ^4.6.5
  get_storage: ^2.0.3
  responsive_builder: ^0.4.2
  provider: ^6.0.3
  cached_network_image: ^3.2.1
  overlay_support: ^2.1.0
  flutter_svg: ^1.1.0
  flutter_lints: ^2.0.2

  #  Network
  dio: ^4.0.6
  connectivity_plus: ^2.3.9
  logger: ^1.1.0

  # Notification
  flutter_local_notifications: ^12.0.3
  firebase_messaging: ^14.2.1

  # Firebase
  firebase_analytics: ^10.1.0
  firebase_core: ^2.11.0
  firebase_auth: ^4.2.4

  #Other
  flutter_widget_from_html: ^0.8.5
  flutter_staggered_animations: ^1.0.0
  shimmer: ^2.0.0
  flutter_slidable: ^2.0.0
  device_info: ^2.0.3
  equatable: ^2.0.3
  flutter_spinkit: ^5.1.0
  keyboard_dismisser: ^3.0.0
  upgrader: ^6.2.0
  custom_timer: ^0.1.1
  animations: ^2.0.7
  flutter_keyboard_visibility: ^5.2.0
  pin_code_fields: ^7.4.0
  flutter_animated_dialog: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  flutter_map: ^3.1.0
  flutter_datetime_picker: ^1.5.1
  image_picker: ^0.8.7+4
  image_cropper: ^1.5.1
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet


flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/jpg/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 100
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 100